// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: proto/proto.proto

package SDT

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//################ POZO JUGADOR LIDER ################
//Mensajes Jugador a Lider
type Jugador_A_Lider_Pozo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitud int32 `protobuf:"varint,1,opt,name=Solicitud,proto3" json:"Solicitud,omitempty"`
}

func (x *Jugador_A_Lider_Pozo) Reset() {
	*x = Jugador_A_Lider_Pozo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador_A_Lider_Pozo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador_A_Lider_Pozo) ProtoMessage() {}

func (x *Jugador_A_Lider_Pozo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador_A_Lider_Pozo.ProtoReflect.Descriptor instead.
func (*Jugador_A_Lider_Pozo) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Jugador_A_Lider_Pozo) GetSolicitud() int32 {
	if x != nil {
		return x.Solicitud
	}
	return 0
}

type Lider_A_Jugador_Pozo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto_Acumulado int32 `protobuf:"varint,1,opt,name=Monto_Acumulado,json=MontoAcumulado,proto3" json:"Monto_Acumulado,omitempty"`
}

func (x *Lider_A_Jugador_Pozo) Reset() {
	*x = Lider_A_Jugador_Pozo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Jugador_Pozo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Jugador_Pozo) ProtoMessage() {}

func (x *Lider_A_Jugador_Pozo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Jugador_Pozo.ProtoReflect.Descriptor instead.
func (*Lider_A_Jugador_Pozo) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Lider_A_Jugador_Pozo) GetMonto_Acumulado() int32 {
	if x != nil {
		return x.Monto_Acumulado
	}
	return 0
}

//################ ETAPA 1 ################
//"En cada ronda se debe verificar cuales jugadores eligieron un número igual o mayor al del Líder. Quienes lo hayan hecho quedan eliminados del juego."
type Jugador_A_Lider_E1_Mayor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugadas []int32 `protobuf:"varint,1,rep,packed,name=Jugadas,proto3" json:"Jugadas,omitempty"`
}

func (x *Jugador_A_Lider_E1_Mayor) Reset() {
	*x = Jugador_A_Lider_E1_Mayor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador_A_Lider_E1_Mayor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador_A_Lider_E1_Mayor) ProtoMessage() {}

func (x *Jugador_A_Lider_E1_Mayor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador_A_Lider_E1_Mayor.ProtoReflect.Descriptor instead.
func (*Jugador_A_Lider_E1_Mayor) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Jugador_A_Lider_E1_Mayor) GetJugadas() []int32 {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

type Lider_A_Jugador_E1_Mayor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eliminados []int32 `protobuf:"varint,1,rep,packed,name=Eliminados,proto3" json:"Eliminados,omitempty"`
}

func (x *Lider_A_Jugador_E1_Mayor) Reset() {
	*x = Lider_A_Jugador_E1_Mayor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Jugador_E1_Mayor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Jugador_E1_Mayor) ProtoMessage() {}

func (x *Lider_A_Jugador_E1_Mayor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Jugador_E1_Mayor.ProtoReflect.Descriptor instead.
func (*Lider_A_Jugador_E1_Mayor) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Lider_A_Jugador_E1_Mayor) GetEliminados() []int32 {
	if x != nil {
		return x.Eliminados
	}
	return nil
}

//"Todos los jugadores que no logren llegar a 21 antes de las 4 rondas serán eliminados"
type Jugador_A_Lider_E1_21 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puntajes []int32 `protobuf:"varint,1,rep,packed,name=Puntajes,proto3" json:"Puntajes,omitempty"`
}

func (x *Jugador_A_Lider_E1_21) Reset() {
	*x = Jugador_A_Lider_E1_21{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador_A_Lider_E1_21) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador_A_Lider_E1_21) ProtoMessage() {}

func (x *Jugador_A_Lider_E1_21) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador_A_Lider_E1_21.ProtoReflect.Descriptor instead.
func (*Jugador_A_Lider_E1_21) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Jugador_A_Lider_E1_21) GetPuntajes() []int32 {
	if x != nil {
		return x.Puntajes
	}
	return nil
}

type Lider_A_Jugador_E1_21 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eliminados []int32 `protobuf:"varint,1,rep,packed,name=Eliminados,proto3" json:"Eliminados,omitempty"`
}

func (x *Lider_A_Jugador_E1_21) Reset() {
	*x = Lider_A_Jugador_E1_21{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Jugador_E1_21) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Jugador_E1_21) ProtoMessage() {}

func (x *Lider_A_Jugador_E1_21) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Jugador_E1_21.ProtoReflect.Descriptor instead.
func (*Lider_A_Jugador_E1_21) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Lider_A_Jugador_E1_21) GetEliminados() []int32 {
	if x != nil {
		return x.Eliminados
	}
	return nil
}

//Fin de la etapa, solicitud de entrada a la siguiente etapa, el lider indica el inicio de la siguiente etapa
type Jugador_A_Lider_Fin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Etapa_Actual int32 `protobuf:"varint,1,opt,name=Etapa_Actual,json=EtapaActual,proto3" json:"Etapa_Actual,omitempty"`
}

func (x *Jugador_A_Lider_Fin) Reset() {
	*x = Jugador_A_Lider_Fin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador_A_Lider_Fin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador_A_Lider_Fin) ProtoMessage() {}

func (x *Jugador_A_Lider_Fin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador_A_Lider_Fin.ProtoReflect.Descriptor instead.
func (*Jugador_A_Lider_Fin) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{6}
}

func (x *Jugador_A_Lider_Fin) GetEtapa_Actual() int32 {
	if x != nil {
		return x.Etapa_Actual
	}
	return 0
}

type Lider_A_Jugador_Fin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta int32 `protobuf:"varint,1,opt,name=Respuesta,proto3" json:"Respuesta,omitempty"`
}

func (x *Lider_A_Jugador_Fin) Reset() {
	*x = Lider_A_Jugador_Fin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Jugador_Fin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Jugador_Fin) ProtoMessage() {}

func (x *Lider_A_Jugador_Fin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Jugador_Fin.ProtoReflect.Descriptor instead.
func (*Lider_A_Jugador_Fin) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{7}
}

func (x *Lider_A_Jugador_Fin) GetRespuesta() int32 {
	if x != nil {
		return x.Respuesta
	}
	return 0
}

//################ ETAPA 2 ################
//"En caso de que el número de jugadores sea impar, se deberá escoger un jugador al azar y eliminarlo del juego"
type Jugador_A_Lider_Eliminar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eliminado int32 `protobuf:"varint,1,opt,name=Eliminado,proto3" json:"Eliminado,omitempty"`
}

func (x *Jugador_A_Lider_Eliminar) Reset() {
	*x = Jugador_A_Lider_Eliminar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador_A_Lider_Eliminar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador_A_Lider_Eliminar) ProtoMessage() {}

func (x *Jugador_A_Lider_Eliminar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador_A_Lider_Eliminar.ProtoReflect.Descriptor instead.
func (*Jugador_A_Lider_Eliminar) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{8}
}

func (x *Jugador_A_Lider_Eliminar) GetEliminado() int32 {
	if x != nil {
		return x.Eliminado
	}
	return 0
}

type Lider_A_Jugador_Eliminar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta int32 `protobuf:"varint,1,opt,name=Respuesta,proto3" json:"Respuesta,omitempty"`
}

func (x *Lider_A_Jugador_Eliminar) Reset() {
	*x = Lider_A_Jugador_Eliminar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Jugador_Eliminar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Jugador_Eliminar) ProtoMessage() {}

func (x *Lider_A_Jugador_Eliminar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Jugador_Eliminar.ProtoReflect.Descriptor instead.
func (*Lider_A_Jugador_Eliminar) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{9}
}

func (x *Lider_A_Jugador_Eliminar) GetRespuesta() int32 {
	if x != nil {
		return x.Respuesta
	}
	return 0
}

//El equipo que logre que la suma de sus valores tenga la misma paridad que el número elegido por el Líder pasará a la siguiente ronda y el otro equipo será eliminado.
type Jugador_A_Lider_E2_Cuerda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puntaje1 int32   `protobuf:"varint,1,opt,name=Puntaje1,proto3" json:"Puntaje1,omitempty"`
	Puntaje2 int32   `protobuf:"varint,2,opt,name=Puntaje2,proto3" json:"Puntaje2,omitempty"`
	Equipo1  []int32 `protobuf:"varint,4,rep,packed,name=Equipo1,proto3" json:"Equipo1,omitempty"`
	Equipo2  []int32 `protobuf:"varint,5,rep,packed,name=Equipo2,proto3" json:"Equipo2,omitempty"`
}

func (x *Jugador_A_Lider_E2_Cuerda) Reset() {
	*x = Jugador_A_Lider_E2_Cuerda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador_A_Lider_E2_Cuerda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador_A_Lider_E2_Cuerda) ProtoMessage() {}

func (x *Jugador_A_Lider_E2_Cuerda) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador_A_Lider_E2_Cuerda.ProtoReflect.Descriptor instead.
func (*Jugador_A_Lider_E2_Cuerda) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{10}
}

func (x *Jugador_A_Lider_E2_Cuerda) GetPuntaje1() int32 {
	if x != nil {
		return x.Puntaje1
	}
	return 0
}

func (x *Jugador_A_Lider_E2_Cuerda) GetPuntaje2() int32 {
	if x != nil {
		return x.Puntaje2
	}
	return 0
}

func (x *Jugador_A_Lider_E2_Cuerda) GetEquipo1() []int32 {
	if x != nil {
		return x.Equipo1
	}
	return nil
}

func (x *Jugador_A_Lider_E2_Cuerda) GetEquipo2() []int32 {
	if x != nil {
		return x.Equipo2
	}
	return nil
}

type Lider_A_Jugador_E2_Cuerda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eliminados []int32 `protobuf:"varint,1,rep,packed,name=Eliminados,proto3" json:"Eliminados,omitempty"`
}

func (x *Lider_A_Jugador_E2_Cuerda) Reset() {
	*x = Lider_A_Jugador_E2_Cuerda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Jugador_E2_Cuerda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Jugador_E2_Cuerda) ProtoMessage() {}

func (x *Lider_A_Jugador_E2_Cuerda) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Jugador_E2_Cuerda.ProtoReflect.Descriptor instead.
func (*Lider_A_Jugador_E2_Cuerda) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{11}
}

func (x *Lider_A_Jugador_E2_Cuerda) GetEliminados() []int32 {
	if x != nil {
		return x.Eliminados
	}
	return nil
}

//################ ETAPA 3 ################
type Jugador_A_Lider_E3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugadas []int32 `protobuf:"varint,1,rep,packed,name=Jugadas,proto3" json:"Jugadas,omitempty"`
	Equipos []int32 `protobuf:"varint,2,rep,packed,name=Equipos,proto3" json:"Equipos,omitempty"`
}

func (x *Jugador_A_Lider_E3) Reset() {
	*x = Jugador_A_Lider_E3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugador_A_Lider_E3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugador_A_Lider_E3) ProtoMessage() {}

func (x *Jugador_A_Lider_E3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugador_A_Lider_E3.ProtoReflect.Descriptor instead.
func (*Jugador_A_Lider_E3) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{12}
}

func (x *Jugador_A_Lider_E3) GetJugadas() []int32 {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

func (x *Jugador_A_Lider_E3) GetEquipos() []int32 {
	if x != nil {
		return x.Equipos
	}
	return nil
}

type Lider_A_Jugador_E3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eliminados []int32 `protobuf:"varint,1,rep,packed,name=Eliminados,proto3" json:"Eliminados,omitempty"`
}

func (x *Lider_A_Jugador_E3) Reset() {
	*x = Lider_A_Jugador_E3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Jugador_E3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Jugador_E3) ProtoMessage() {}

func (x *Lider_A_Jugador_E3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Jugador_E3.ProtoReflect.Descriptor instead.
func (*Lider_A_Jugador_E3) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{13}
}

func (x *Lider_A_Jugador_E3) GetEliminados() []int32 {
	if x != nil {
		return x.Eliminados
	}
	return nil
}

//################ LIDER A POZO ################
type Lider_A_Pozo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitud int32 `protobuf:"varint,1,opt,name=Solicitud,proto3" json:"Solicitud,omitempty"`
}

func (x *Lider_A_Pozo) Reset() {
	*x = Lider_A_Pozo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Pozo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Pozo) ProtoMessage() {}

func (x *Lider_A_Pozo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Pozo.ProtoReflect.Descriptor instead.
func (*Lider_A_Pozo) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{14}
}

func (x *Lider_A_Pozo) GetSolicitud() int32 {
	if x != nil {
		return x.Solicitud
	}
	return 0
}

type Pozo_A_Lider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto_Acumulado int32 `protobuf:"varint,1,opt,name=Monto_Acumulado,json=MontoAcumulado,proto3" json:"Monto_Acumulado,omitempty"`
}

func (x *Pozo_A_Lider) Reset() {
	*x = Pozo_A_Lider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pozo_A_Lider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pozo_A_Lider) ProtoMessage() {}

func (x *Pozo_A_Lider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pozo_A_Lider.ProtoReflect.Descriptor instead.
func (*Pozo_A_Lider) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{15}
}

func (x *Pozo_A_Lider) GetMonto_Acumulado() int32 {
	if x != nil {
		return x.Monto_Acumulado
	}
	return 0
}

type ArregloLider_A_Pozo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Muertos []int32 `protobuf:"varint,1,rep,packed,name=Muertos,proto3" json:"Muertos,omitempty"`
	Etapa   int32   `protobuf:"varint,2,opt,name=Etapa,proto3" json:"Etapa,omitempty"`
}

func (x *ArregloLider_A_Pozo) Reset() {
	*x = ArregloLider_A_Pozo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArregloLider_A_Pozo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArregloLider_A_Pozo) ProtoMessage() {}

func (x *ArregloLider_A_Pozo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArregloLider_A_Pozo.ProtoReflect.Descriptor instead.
func (*ArregloLider_A_Pozo) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{16}
}

func (x *ArregloLider_A_Pozo) GetMuertos() []int32 {
	if x != nil {
		return x.Muertos
	}
	return nil
}

func (x *ArregloLider_A_Pozo) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type ArregloPozo_A_Lider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta int32 `protobuf:"varint,1,opt,name=Respuesta,proto3" json:"Respuesta,omitempty"`
}

func (x *ArregloPozo_A_Lider) Reset() {
	*x = ArregloPozo_A_Lider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArregloPozo_A_Lider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArregloPozo_A_Lider) ProtoMessage() {}

func (x *ArregloPozo_A_Lider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArregloPozo_A_Lider.ProtoReflect.Descriptor instead.
func (*ArregloPozo_A_Lider) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{17}
}

func (x *ArregloPozo_A_Lider) GetRespuesta() int32 {
	if x != nil {
		return x.Respuesta
	}
	return 0
}

type Lider_A_Namenode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugadas []int32 `protobuf:"varint,1,rep,packed,name=Jugadas,proto3" json:"Jugadas,omitempty"` // Las jugadas van en la posición del jugador en el arreglo
	Etapa   int32   `protobuf:"varint,2,opt,name=Etapa,proto3" json:"Etapa,omitempty"`
}

func (x *Lider_A_Namenode) Reset() {
	*x = Lider_A_Namenode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lider_A_Namenode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lider_A_Namenode) ProtoMessage() {}

func (x *Lider_A_Namenode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lider_A_Namenode.ProtoReflect.Descriptor instead.
func (*Lider_A_Namenode) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{18}
}

func (x *Lider_A_Namenode) GetJugadas() []int32 {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

func (x *Lider_A_Namenode) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type Namenode_A_Lider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta int32 `protobuf:"varint,1,opt,name=Respuesta,proto3" json:"Respuesta,omitempty"` //un 1 si registra al jugador, un 0 si no
}

func (x *Namenode_A_Lider) Reset() {
	*x = Namenode_A_Lider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namenode_A_Lider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namenode_A_Lider) ProtoMessage() {}

func (x *Namenode_A_Lider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namenode_A_Lider.ProtoReflect.Descriptor instead.
func (*Namenode_A_Lider) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{19}
}

func (x *Namenode_A_Lider) GetRespuesta() int32 {
	if x != nil {
		return x.Respuesta
	}
	return 0
}

type Namenode_A_Datanode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada  int32 `protobuf:"varint,1,opt,name=Jugada,proto3" json:"Jugada,omitempty"`
	Jugador int32 `protobuf:"varint,2,opt,name=Jugador,proto3" json:"Jugador,omitempty"`
	Etapa   int32 `protobuf:"varint,3,opt,name=Etapa,proto3" json:"Etapa,omitempty"`
}

func (x *Namenode_A_Datanode) Reset() {
	*x = Namenode_A_Datanode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namenode_A_Datanode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namenode_A_Datanode) ProtoMessage() {}

func (x *Namenode_A_Datanode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namenode_A_Datanode.ProtoReflect.Descriptor instead.
func (*Namenode_A_Datanode) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{20}
}

func (x *Namenode_A_Datanode) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

func (x *Namenode_A_Datanode) GetJugador() int32 {
	if x != nil {
		return x.Jugador
	}
	return 0
}

func (x *Namenode_A_Datanode) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type Datanode_A_Namenode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *Datanode_A_Namenode) Reset() {
	*x = Datanode_A_Namenode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proto_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Datanode_A_Namenode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datanode_A_Namenode) ProtoMessage() {}

func (x *Datanode_A_Namenode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datanode_A_Namenode.ProtoReflect.Descriptor instead.
func (*Datanode_A_Namenode) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{21}
}

func (x *Datanode_A_Namenode) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

var File_proto_proto_proto protoreflect.FileDescriptor

var file_proto_proto_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x14, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x50, 0x6f,
	0x7a, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64,
	0x22, 0x3f, 0x0a, 0x14, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x27, 0x0a, 0x0f, 0x4d, 0x6f, 0x6e, 0x74,
	0x6f, 0x5f, 0x41, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x41, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x64,
	0x6f, 0x22, 0x34, 0x0a, 0x18, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x45, 0x31, 0x5f, 0x4d, 0x61, 0x79, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x22, 0x3a, 0x0a, 0x18, 0x4c, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x45, 0x31, 0x5f, 0x4d, 0x61,
	0x79, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61,
	0x64, 0x6f, 0x73, 0x22, 0x33, 0x0a, 0x15, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41,
	0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x45, 0x31, 0x5f, 0x32, 0x31, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x75, 0x6e, 0x74, 0x61, 0x6a, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08,
	0x50, 0x75, 0x6e, 0x74, 0x61, 0x6a, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x15, 0x4c, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x45, 0x31, 0x5f, 0x32,
	0x31, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f,
	0x73, 0x22, 0x38, 0x0a, 0x13, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x46, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x45, 0x74, 0x61, 0x70,
	0x61, 0x5f, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x45, 0x74, 0x61, 0x70, 0x61, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x22, 0x33, 0x0a, 0x13, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x46,
	0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x22, 0x38, 0x0a, 0x18, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x22, 0x38, 0x0a, 0x18, 0x4c, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x45, 0x6c,
	0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x22, 0x87, 0x01, 0x0a, 0x19, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x45, 0x32, 0x5f, 0x43, 0x75, 0x65, 0x72,
	0x64, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x75, 0x6e, 0x74, 0x61, 0x6a, 0x65, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x75, 0x6e, 0x74, 0x61, 0x6a, 0x65, 0x31, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x75, 0x6e, 0x74, 0x61, 0x6a, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x50, 0x75, 0x6e, 0x74, 0x61, 0x6a, 0x65, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6f, 0x31, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x6f, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6f, 0x32, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6f, 0x32, 0x22, 0x3b,
	0x0a, 0x19, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x5f, 0x45, 0x32, 0x5f, 0x43, 0x75, 0x65, 0x72, 0x64, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x45,
	0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0a, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x73, 0x22, 0x48, 0x0a, 0x12, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x45,
	0x33, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6f, 0x73, 0x22, 0x34, 0x0a, 0x12, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41,
	0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x45, 0x33, 0x12, 0x1e, 0x0a, 0x0a, 0x45,
	0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0a, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x73, 0x22, 0x2c, 0x0a, 0x0c, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x53,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x22, 0x37, 0x0a, 0x0c, 0x50, 0x6f, 0x7a,
	0x6f, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x4d, 0x6f, 0x6e,
	0x74, 0x6f, 0x5f, 0x41, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x41, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61,
	0x64, 0x6f, 0x22, 0x45, 0x0a, 0x13, 0x41, 0x72, 0x72, 0x65, 0x67, 0x6c, 0x6f, 0x4c, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x41, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x75, 0x65,
	0x72, 0x74, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x75, 0x65, 0x72,
	0x74, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x74, 0x61, 0x70, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22, 0x33, 0x0a, 0x13, 0x41, 0x72, 0x72,
	0x65, 0x67, 0x6c, 0x6f, 0x50, 0x6f, 0x7a, 0x6f, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x42,
	0x0a, 0x10, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x74, 0x61, 0x70, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x74, 0x61,
	0x70, 0x61, 0x22, 0x30, 0x0a, 0x10, 0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x41,
	0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x13, 0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x41, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x74, 0x61, 0x70, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x74,
	0x61, 0x70, 0x61, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x41, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x32, 0xad, 0x04, 0x0a, 0x1a, 0x43,
	0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x5f, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x0c, 0x45, 0x74, 0x61,
	0x70, 0x61, 0x31, 0x5f, 0x4d, 0x61, 0x79, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x45, 0x31, 0x5f, 0x4d, 0x61, 0x79, 0x6f, 0x72, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x6f, 0x72, 0x5f, 0x45, 0x31, 0x5f, 0x4d, 0x61, 0x79, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x06, 0x43, 0x75, 0x61, 0x74, 0x72, 0x6f, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f,
	0x45, 0x31, 0x5f, 0x32, 0x31, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x45, 0x31,
	0x5f, 0x32, 0x31, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x06, 0x45, 0x74, 0x61, 0x70, 0x61, 0x32, 0x12,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f,
	0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x45, 0x32, 0x5f, 0x43, 0x75, 0x65, 0x72, 0x64,
	0x61, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f,
	0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x45, 0x32, 0x5f, 0x43, 0x75, 0x65,
	0x72, 0x64, 0x61, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x06, 0x45, 0x74, 0x61, 0x70, 0x61, 0x33, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f,
	0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x45, 0x33, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64,
	0x6f, 0x72, 0x5f, 0x45, 0x33, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x5f, 0x45,
	0x74, 0x61, 0x70, 0x61, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x46, 0x69, 0x6e,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41,
	0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x46, 0x69, 0x6e, 0x22, 0x00, 0x12, 0x4e,
	0x0a, 0x08, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x1a, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x5f, 0x45, 0x6c, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x22, 0x00, 0x12, 0x4a,
	0x0a, 0x0c, 0x50, 0x6f, 0x7a, 0x6f, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x41,
	0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x22, 0x00, 0x32, 0x9d, 0x01, 0x0a, 0x17, 0x43,
	0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x5f, 0x4c, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x38, 0x0a, 0x0a, 0x50, 0x6f, 0x7a, 0x6f, 0x5f, 0x4c,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x41, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x7a, 0x6f, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x22, 0x00,
	0x12, 0x48, 0x0a, 0x0c, 0x41, 0x72, 0x72, 0x65, 0x67, 0x6c, 0x6f, 0x5f, 0x50, 0x6f, 0x7a, 0x6f,
	0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x72, 0x65, 0x67, 0x6c, 0x6f,
	0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x50, 0x6f, 0x7a, 0x6f, 0x1a, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x72, 0x65, 0x67, 0x6c, 0x6f, 0x50, 0x6f, 0x7a, 0x6f,
	0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x22, 0x00, 0x32, 0x62, 0x0a, 0x1b, 0x43, 0x6f,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x45, 0x6e, 0x76,
	0x69, 0x61, 0x72, 0x5f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x41, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x41, 0x5f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x22, 0x00, 0x32, 0x6c,
	0x0a, 0x1e, 0x43, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x5f, 0x4e,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x4a, 0x0a, 0x0e, 0x47, 0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x5f, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x41, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x41, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x53, 0x61, 0x6e, 0x73,
	0x61, 0x6e, 0x61, 0x2f, 0x53, 0x44, 0x54, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData = file_proto_proto_proto_rawDesc
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_proto_proto_rawDescData)
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_proto_proto_goTypes = []interface{}{
	(*Jugador_A_Lider_Pozo)(nil),      // 0: proto.Jugador_A_Lider_Pozo
	(*Lider_A_Jugador_Pozo)(nil),      // 1: proto.Lider_A_Jugador_Pozo
	(*Jugador_A_Lider_E1_Mayor)(nil),  // 2: proto.Jugador_A_Lider_E1_Mayor
	(*Lider_A_Jugador_E1_Mayor)(nil),  // 3: proto.Lider_A_Jugador_E1_Mayor
	(*Jugador_A_Lider_E1_21)(nil),     // 4: proto.Jugador_A_Lider_E1_21
	(*Lider_A_Jugador_E1_21)(nil),     // 5: proto.Lider_A_Jugador_E1_21
	(*Jugador_A_Lider_Fin)(nil),       // 6: proto.Jugador_A_Lider_Fin
	(*Lider_A_Jugador_Fin)(nil),       // 7: proto.Lider_A_Jugador_Fin
	(*Jugador_A_Lider_Eliminar)(nil),  // 8: proto.Jugador_A_Lider_Eliminar
	(*Lider_A_Jugador_Eliminar)(nil),  // 9: proto.Lider_A_Jugador_Eliminar
	(*Jugador_A_Lider_E2_Cuerda)(nil), // 10: proto.Jugador_A_Lider_E2_Cuerda
	(*Lider_A_Jugador_E2_Cuerda)(nil), // 11: proto.Lider_A_Jugador_E2_Cuerda
	(*Jugador_A_Lider_E3)(nil),        // 12: proto.Jugador_A_Lider_E3
	(*Lider_A_Jugador_E3)(nil),        // 13: proto.Lider_A_Jugador_E3
	(*Lider_A_Pozo)(nil),              // 14: proto.Lider_A_Pozo
	(*Pozo_A_Lider)(nil),              // 15: proto.Pozo_A_Lider
	(*ArregloLider_A_Pozo)(nil),       // 16: proto.ArregloLider_A_Pozo
	(*ArregloPozo_A_Lider)(nil),       // 17: proto.ArregloPozo_A_Lider
	(*Lider_A_Namenode)(nil),          // 18: proto.Lider_A_Namenode
	(*Namenode_A_Lider)(nil),          // 19: proto.Namenode_A_Lider
	(*Namenode_A_Datanode)(nil),       // 20: proto.Namenode_A_Datanode
	(*Datanode_A_Namenode)(nil),       // 21: proto.Datanode_A_Namenode
}
var file_proto_proto_proto_depIdxs = []int32{
	2,  // 0: proto.Comunicacion_Jugador_Lider.Etapa1_Mayor:input_type -> proto.Jugador_A_Lider_E1_Mayor
	4,  // 1: proto.Comunicacion_Jugador_Lider.Cuatro:input_type -> proto.Jugador_A_Lider_E1_21
	10, // 2: proto.Comunicacion_Jugador_Lider.Etapa2:input_type -> proto.Jugador_A_Lider_E2_Cuerda
	12, // 3: proto.Comunicacion_Jugador_Lider.Etapa3:input_type -> proto.Jugador_A_Lider_E3
	6,  // 4: proto.Comunicacion_Jugador_Lider.Fin_Etapa:input_type -> proto.Jugador_A_Lider_Fin
	8,  // 5: proto.Comunicacion_Jugador_Lider.Eliminar:input_type -> proto.Jugador_A_Lider_Eliminar
	0,  // 6: proto.Comunicacion_Jugador_Lider.Pozo_Jugador:input_type -> proto.Jugador_A_Lider_Pozo
	14, // 7: proto.Comunicacion_Lider_Pozo.Pozo_Lider:input_type -> proto.Lider_A_Pozo
	16, // 8: proto.Comunicacion_Lider_Pozo.Arreglo_Pozo:input_type -> proto.ArregloLider_A_Pozo
	18, // 9: proto.Comunicacion_Lider_Namenode.Enviar_Jugada:input_type -> proto.Lider_A_Namenode
	20, // 10: proto.Comunicacion_Namenode_Datanode.Guardar_Jugada:input_type -> proto.Namenode_A_Datanode
	3,  // 11: proto.Comunicacion_Jugador_Lider.Etapa1_Mayor:output_type -> proto.Lider_A_Jugador_E1_Mayor
	5,  // 12: proto.Comunicacion_Jugador_Lider.Cuatro:output_type -> proto.Lider_A_Jugador_E1_21
	11, // 13: proto.Comunicacion_Jugador_Lider.Etapa2:output_type -> proto.Lider_A_Jugador_E2_Cuerda
	13, // 14: proto.Comunicacion_Jugador_Lider.Etapa3:output_type -> proto.Lider_A_Jugador_E3
	7,  // 15: proto.Comunicacion_Jugador_Lider.Fin_Etapa:output_type -> proto.Lider_A_Jugador_Fin
	9,  // 16: proto.Comunicacion_Jugador_Lider.Eliminar:output_type -> proto.Lider_A_Jugador_Eliminar
	1,  // 17: proto.Comunicacion_Jugador_Lider.Pozo_Jugador:output_type -> proto.Lider_A_Jugador_Pozo
	15, // 18: proto.Comunicacion_Lider_Pozo.Pozo_Lider:output_type -> proto.Pozo_A_Lider
	17, // 19: proto.Comunicacion_Lider_Pozo.Arreglo_Pozo:output_type -> proto.ArregloPozo_A_Lider
	19, // 20: proto.Comunicacion_Lider_Namenode.Enviar_Jugada:output_type -> proto.Namenode_A_Lider
	21, // 21: proto.Comunicacion_Namenode_Datanode.Guardar_Jugada:output_type -> proto.Datanode_A_Namenode
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador_A_Lider_Pozo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Jugador_Pozo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador_A_Lider_E1_Mayor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Jugador_E1_Mayor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador_A_Lider_E1_21); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Jugador_E1_21); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador_A_Lider_Fin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Jugador_Fin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador_A_Lider_Eliminar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Jugador_Eliminar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador_A_Lider_E2_Cuerda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Jugador_E2_Cuerda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugador_A_Lider_E3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Jugador_E3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Pozo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pozo_A_Lider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArregloLider_A_Pozo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArregloPozo_A_Lider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lider_A_Namenode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namenode_A_Lider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namenode_A_Datanode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proto_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Datanode_A_Namenode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_rawDesc = nil
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
